variables:
  - group: Keys
trigger: none
pool:
  vmImage: windows-2019
steps:
- checkout: self
  clean: true
- task: PowerShell@2
  displayName: Checkpoint-GitHubIssue
  inputs:
    pwsh: true
    targetType: filePath
    filePath: .\Scripts\Checkpoint-GitHubIssue.ps1 
    arguments: $(GitHubUserName) $(GitHubPass) $(ProjectName)






