variables:
  - group: Keys
trigger: none
pool:
  vmImage: windows-latest
steps:
- checkout: self
  clean: true
- task: PowerShell@2
  displayName: Checkpoint-GitHubIssue
  inputs:
    pwsh: true
    targetType: inline
    script: |
      set-location '$(System.DefaultWorkingDirectory)'
      $ErrorView="NormalView"
      $VerbosePreference="Continue"
      .\Scripts\Checkpoint-GitHubIssue.ps1 $(GitHubUserName) $(GitHubToken) $(ProjectName)






