variables:
  - group: Keys
trigger: none
pool:
  vmImage: vs2017-win2016
steps:
- checkout: self
  clean: true
- task: PowerShell@2
  displayName: Checkpoint-GitHubIssue
  inputs:
    targetType: filePath
    filePath: .\Scripts\Checkpoint-GitHubIssue.ps1 $(ProjectName)
    arguments: $(GitHubUserName) $(GitHubPass)






