# https://aka.ms/yaml
variables:
  - group: Keys
trigger: 
  paths:
     include:
      - /Close-GitHubIssue-ForAge.yml
  branches:
     include:
       - master
pool:
  vmImage: vs2017-win2016
steps:
- checkout: self
  clean: true
- powershell: |
   $VerbosePreference="continue"
   Install-Module XpandPosh -RequiredVersion 1.0.34 -Scope CurrentUser -Force -Repository PSGallery
   Close-GithubIssue -Repository1 eXpand -GitHubApp eXpandFramework -Owner $(GithubUserName) -Pass $(GithubPass) -Organization eXpandFramework
  failOnStderr: true
  displayName: CloseIssueForAge





