# https://aka.ms/yaml
variables:
  - group: Keys
trigger: 
  paths:
     include:
      - /Close-GitHubIssue-ForAge.yml
  branches:
     include:
       - master
pool:
  vmImage: windows-2019
steps:
- checkout: self
  clean: true
- task: PowerShell@2
  displayName: CloseIssueForAge
  inputs:
    pwsh: true
    targetType: filePath
    filePath: .\Scripts\Close-GitHubIssue-ForAge.ps1 
    arguments: $(GitHubUserName) $(eXpandGitHubToken) 




