# https://aka.ms/yaml
variables:
  - group: Keys
trigger: none
pool:
  vmImage: windows-2019
steps:
- checkout: self
  clean: true
- task: AzurePowerShell@5
  name: BuildNugetConsumers
  inputs:
    errorActionPreference: stop
    FailOnStandardError: true
    azureSubscription: 'Visual Studio Enterprise(b48a609a-17f6-4e48-a317-54ab77fbf822)'
    ScriptType: 'InlineScript'
    azurePowerShellVersion: 'LatestVersion'
    pwsh: true
    Inline: |
      $ErrorActionPreference="stop"
      $ErrorView="NormalView"
      $yaml = @"
      - Name: XpandPwsh
        Version: 1.221.0.13
      "@
      & '$(System.DefaultWorkingDirectory)\Scripts\Install-Module.ps1' $yaml
      $VerbosePreference="Continue"
      & '$(System.DefaultWorkingDirectory)\Scripts\DevExpress.XAF-GitHub-Release.ps1' '$(AzureToken)' '$(System.ArtifactsDirectory)' '$(GitHubToken)' '$(GitHubPass)' '$(DXApiFeed)' '$(GitHubUserEmail)'


