# https://aka.ms/yaml
variables:
  - group: Keys
trigger: none
pool:
  vmImage: windows-latest
steps:
- checkout: self
  clean: true
- task: AzurePowerShell@5
  name: BuildNugetConsumers
  inputs:
    errorActionPreference: stop
    FailOnStandardError: true
    azureSubscription: '2026_1'
    ScriptType: 'InlineScript'
    azurePowerShellVersion: 'LatestVersion'
    pwsh: true
    Inline: |
      $ErrorActionPreference="stop"
      $ErrorView="NormalView"
      $yaml = @"
      - Name: XpandPwsh
        Version: 1.221.0.20
      "@
      & '$(System.DefaultWorkingDirectory)\Scripts\Install-Module.ps1' $yaml
      
      & '$(System.DefaultWorkingDirectory)\Scripts\DevExpress.XAF-GitHub-Release.ps1' '$(AzureToken)' '$(System.ArtifactsDirectory)' '$(GitHubToken)' '$(GitHubPass)' '$(DXApiFeed)' '$(GitHubUserEmail)'


