# https://aka.ms/yaml
variables:
  - group: Keys
trigger: none
pool:
  vmImage: vs2017-win2016
steps:
- checkout: self
  clean: true
- task: PowerShell@2
  displayName: Publish
  inputs:
    targetType: filePath
    filePath: .\Scripts\Index-DevExpress-Packages-Contents.ps1
    arguments: $(GitHubUserName) $(GitHubPass) $(GitHubUserEmail) $(DXApiFeed)
    
