# https://aka.ms/yaml
variables:
  - group: Keys
trigger: none
pool:
  vmImage: windows-2019
steps:
- checkout: self
  clean: true
- task: PowerShell@2
  displayName: Release
  inputs:
    pwsh: true
    targetType: filePath
    filePath: .\Scripts\Label-Issues.ps1
    arguments: $(GitHubUserName)  $(GitHubPass) 
    
