# https://aka.ms/yaml
variables:
  - group: Keys
trigger: none
pool:
  vmImage: windows-2019
steps:
- checkout: self
  clean: true
- task: PowerShell@2
  displayName: Release
  inputs:
    pwsh: true
    targetType: filePath
    filePath: .\Scripts\Notify-New-DevExpress.Version.ps1
    arguments: $(DXApiFeed) $(TwitterAPIKey) $(TwitterAPISecret) $(TwitterAccessToken) $(TwitterAccessTokenSecret)
