# https://aka.ms/yaml
variables:
  - group: Keys
trigger: none
pool:
  vmImage: windows-2019
steps:
- checkout: self
  clean: true
- task: PowerShell@2
  displayName: Publish
  inputs:
    pwsh: true
    targetType: inline
    script: |
      $ErrorView="NormalView"
      $VerbosePreference="continue"
      $(System.DefaultWorkingDirectory)\Scripts\Publish-Nuget-Packages.ps1 '$(AzureToken)' '$(System.ArtifactsDirectory)' '$(NugetApiKey)' '$(AzApoPowerSHellScriptsSecret)' '$(AzPowerShellScriptsApplicationId)' '$(AzApoTenantId)'
    

