# https://aka.ms/yaml
variables:
  - group: Keys
trigger: none
pool:
  vmImage: vs2017-win2016
steps:
- checkout: self
  clean: true
- powershell: |
    Write-Host "Installing XpandPosh"
    Install-Module XpandPosh -RequiredVersion 1.0.43 -Scope CurrentUser -Force -Repository PSGallery -Verbose
    $version=Get-XpandVersion -Latest
    Set-VsoVariable artifact Xpand.v$version
    Set-VsoVariable version $version
    Write-Host "Installing VSTeam"
    Install-Module VSTeam -Scope CurrentUser -Force -Repository PSGallery -Verbose
    Set-VSTeamAccount -Account eXpandDevOps -PersonalAccessToken $(AzureToken)
    $build = (Get-VSTeamBuild -ProjectName eXpandFramework|Where-Object {$_.DefinitionName -like "Xpand-Lab" -and $_.Result -eq "succeeded"}|Select-Object -First 1).id
    Write-Host "build=$build"
    Set-VsoVariable buildId $build
  displayName: Init
- task: DownloadBuildArtifacts@0
  displayName: 'Download Build Artifacts'
  inputs:
    buildType: specific
    project: 'dc0010e5-9ecf-45ac-b89d-2d51897f3855'
    pipeline: 32
    buildVersionToDownload: specific
    buildId: $(buildId)
    artifactName: $(artifact)
    downloadPath: $(System.ArtifactsDirectory)
- powershell: |
    Set-location 
    Expand-Archive "$(System.ArtifactsDirectory)\Nupkg-$version.zip" -destinationpath $(System.ArtifactsDirectory)
    $publishNugetFeed="https://xpandnugetserver.azurewebsites.net/nuget"
    Publish-NugetPackage $(System.ArtifactsDirectory) $publishNugetFeed $(nugetApiKey) -Verbose
  displayName: Release

