# https://aka.ms/yaml
variables:
  - group: Keys
trigger: none
pool:
  vmImage: windows-2019
steps:
- checkout: self
  clean: true
- task: PowerShell@2
  displayName: Publish
  inputs:
    pwsh: true
    targetType: filePath
    filePath: .\Scripts\Publish-Nuget-Packages.ps1
    arguments: $(AzureToken) $(System.ArtifactsDirectory) $(NugetApiKey) 
    

