# https://aka.ms/yaml
variables:
  - group: Keys
trigger: none
pool:
  vmImage: windows-2019
steps:
- checkout: self
  clean: true
- task: PowerShell@2
  displayName: Release
  continueOnError: false
  inputs:
    errorActionPreference: stop
    pwsh: true
    failOnStderr: true
    targetType: filePath
    filePath: .\Scripts\Test-Installer-Script.ps1
    arguments: $(GitHubUserName) $(GitHubPass)
