# https://aka.ms/yaml
variables:
  - group: Keys
  
trigger: none
pool:
  vmImage: windows-2019
steps:
- checkout: self
  clean: true
- task: PowerShell@2
  displayName: Twitter
  inputs:
    pwsh: true
    targetType: inline
    script: |
      $ErrorView="NormalView"
      $VerbosePreference="Continue"
      write-host "script"
      $env:SCRIPTNAME
      Set-Location '$(System.DefaultWorkingDirectory)'
      $a=@{
        TwitterAPIKey = '$(TwitterAPIKey)' 
        TwitterAPISecret = '$(TwitterAPISecret)' 
        TwitterAccessToken = '$(TwitterAccessToken)' 
        TwitterAccessTokenSecret = '$(TwitterAccessTokenSecret)' 
        MyTwitterAPIKey = '$(MyTwitterAPIKey)' 
        MyTwitterAPISecret = '$(MyTwitterAPISecret)' 
        MyTwitterAccessToken = '$(MyTwitterAccessToken)' 
        MyTwitterAccessTokenSecret = '$(MyTwitterAccessTokenSecret)' 
        AzureApptwittlicationId = '$(AzureApplicationId)' 
        AzureTenantId = '$(AzureTenantId)' 
        XpandBlobOwnerSecret = '$(XpandBlobOwnerSecret)'
        Test ='test'
        ScriptName = $env:ScriptName
      }
      $a|Out-string
      # write-Verbose -Verbose  "##vso[task.setvariable variable=ssss;]$a.XpandBlobOwnerSecret"
      & ".\Scripts\Twitter.ps1" @a
    
