# https://aka.ms/yaml
variables:
  - group: Keys
trigger: none
pool:
  vmImage: vs2017-win2016
steps:
- checkout: self
  clean: true
- powershell: |
    Write-Host "Installing XpandPosh"
    Install-Module XpandPosh -RequiredVersion 1.0.38 -Scope CurrentUser -Force -Repository PSGallery -Verbose
    $version=Get-XpandVersion -Latest
    Set-VsoVariable artifact Xpand.v$version
    Write-Host "Installing VSTeam"
    Install-Module VSTeam -Scope CurrentUser -Force -Repository PSGallery -Verbose
    Set-VSTeamAccount -Account eXpandDevOps -PersonalAccessToken $(AzureToken)
    $build = (Get-VSTeamBuild -ProjectName eXpandFramework|Where-Object {$_.DefinitionName -like "Xpand-Lab" -and $_.Result -eq "succeeded"}|Select-Object -First 1).id
    Write-Host "build=$build"
    Set-VsoVariable buildId $build
  displayName: Init
- task: DownloadBuildArtifacts@0
  displayName: 'Download Build Artifacts'
  inputs:
    buildType: specific
    project: 'dc0010e5-9ecf-45ac-b89d-2d51897f3855'
    pipeline: 32
    buildVersionToDownload: specific
    buildId: $(buildId)
    artifactName: $(artifact)
    downloadPath: $(System.ArtifactsDirectory)
- powershell: |
    Set-location "D:\a\1\a"
    Get-ChildItem
    $commitIssues=Get-GitHubCommitIssue -Repository1 eXpand -Repository2 lab -Owner $(GitHubUserName) -Pass $(GitHubPass) -Organization eXpandFramework
    $commitIssues
    $notes=New-GithubReleaseNotes -Repository1 eXpand -Repository2 lab -Owner $(GitHubUserName) -ReleaseNotesTemplate (New-GithubReleaseNotesTemplate) -Organization eXpandFramework -Pass $(GitHubPass) -CommitIssues $commitIssues
    $notes
    $files=Get-ChildItem $(System.ArtifactsDirectory) -Recurse|Select-Object -ExpandProperty FullName
    $files
    $milestone=(Get-GitHubMilestone -Repository eXpand -Owner $(GitHubUserName) -Organization eXpandFramework -Pass $(GitHubPass) -Verbose -Latest).Title
    $milestone
    Publish-GitHubRelease -Owner $(GitHubUserName) -Organization eXpandFramework -Repository lab -ReleaseName $milestone -ReleaseNotes $notes -Pass $(GitHubPass) -Verbose -Files $files
  displayName: Release

