# https://aka.ms/yaml
variables:
  - group: Keys
trigger: none
pool:
  vmImage: windows-latest
steps:
- checkout: self
  clean: true
- task: PowerShell@2
  displayName: Release
  inputs:
    pwsh: true
    targetType: filePath
    filePath: .\Scripts\Xpand-GitHub-Release.ps1
    arguments: $(AzureToken) $(System.ArtifactsDirectory) $(GitHubToken) $(GitHubPass) $(GitHubUserEmail) $(DXApiFeed)

