# https://aka.ms/yaml
variables:
  - group: Keys
trigger: none
pool:
  vmImage: windows-2019
steps:
- checkout: self
  clean: true
- task: PowerShell@2
  displayName: Release
  inputs:
    targetType: filePath
    filePath: .\Scripts\Xpand-GitHub-Release.ps1
    arguments: $(AzureToken) $(System.ArtifactsDirectory) $(GitHubUserName) $(GitHubPass)

